### ISSUE TITLE
Heimdall sync without an already synced BOR

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#148]
Currently `heimdall` fetches checkpoint data from `bor` and `bor` fetches span data from `heimdall`. While this solves a lot of problems it creates an issue when we are trying to sync nodes, because to evaluate the checkpoint data while syncing `heimdall` node needs a fully synched `bor` node. 

We want to evaluate different ways to solve this using this issue.

**Comment by jdkanani** [comment]
### Proposal 1

Instead of querying Bor block headers and computing `rootHash` in the transaction ([here](https://github.com/maticnetwork/heimdall/blob/master/checkpoint/handler.go#L35-L151)), this proposal proposes to "propose & vote checkpoint by transaction" mechanism.

The checkpoint proposer will propose the checkpoint by sending `MsgProposeCheckpoint` on Heimdall:

```go
type MsgProposeCheckpoint struct {
	Proposer        types.HeimdallAddress `json:"proposer"`
	StartBlock      uint64                `json:"startBlock"`
	EndBlock        uint64                `json:"endBlock"`
	RootHash        types.HeimdallHash    `json:"rootHash"`
	AccountRootHash types.HeimdallHash    `json:"accountRootHash"`
	TimeStamp       uint64                `json:"timestamp"`
	Sig             []byte                `json:"sig"`
}
```

Where `Sig` is proposer's signature on `message`, 

```go
message := keccak256(Proposer, StartBlock, EndBlock, RootHash, AccountRootHash)
Sig := ethCrypto.Sign(message, privKey)
```

Once the proposer proposes the checkpoint successfully and their tx gets included in the block on Heimdall, each validator will validate if a proposed checkpoint is valid. They will send `MsgVoteCheckpoint` in case the checkpoint is valid.

```go
type MsgVoteCheckpoint struct {
	Proposer        types.HeimdallAddress `json:"proposer"`
	StartBlock      uint64                `json:"startBlock"`
	EndBlock        uint64                `json:"endBlock"`
	RootHash        types.HeimdallHash    `json:"rootHash"`
	AccountRootHash types.HeimdallHash    `json:"accountRootHash"`
	TimeStamp       uint64                `json:"timestamp"`
	Sig             []byte                `json:"sig"`
}
```

**Effect on sync**

With this proposal, Heimdall will be making external calls or depends on Bor while syncing. In the end, Heimdall can be synced without already synced Bor node.

**Comment by vaibhavchellani** [comment]
I have multiple issues with this proposal. 

- Validators won't be actually validating the sidechain state and attesting to it. 
- What currently takes 1 transaction will take 300 transactions and probably even more if there are situations that require `NACK`. 
- What currently takes `X` fees will take (300^X) fees
- Will bloat the sidechain state quite a lot
- We will have to ensure that the heimdall chain is high throughput otherwise other essential system functionalities like `span` and `state-sync` will get affected
- Things on the bridge will also start getting complicated, for creating a checkpoint you have to fetch 300 transactions
- Economics might also be affected, since producing checkpoint costs far more than before.

**Comment by jdkanani** [comment]
> Validators won't be actually validating the sidechain state and attesting to it.

It can be done at bridge side. In either case, the validator can choose not to compute the state. 

> What currently takes 1 transaction will take 300 transactions and probably even more if there are situations that require NACK

No NACK required. We can tally votes in EndBlocker as `x/gov` does.

> We will have to ensure that the Heimdall chain is high throughput otherwise other essential system functionalities like span and state-sync will get affected

Yeah but multiple checkpoints voting can be done in parallel and those transactions can be processed easily in 10 mins interval. We can optimize by creating bulk fetch checkpoint votes tx from the mempool.

> Things on the bridge will also start getting complicated, for creating a checkpoint you have to fetch 300 transactions

No need to fetch all transactions. One query will do it from the state. 

> Economics might also be affected, since producing checkpoint costs far more than before.

Similar to `x/gov`, we can refund fees or checkpoint deposits if it receives 2/3+1 positive votes.

**Comment by 0xAshish** [comment]
@jdkanani @vaibhavchellani I like proposal 1 a lot and I would suggest if we can make it like this
- Only one of the validators sends this tx and everyone else validates it.
- Once that tx is buried under one checkpoint we have 2/3+1 consensus
Essentially eliminating the need for 300 txs yet getting 2/3+1 security.

**Comment by 0xAshish** [comment]
I think we should move this attestation process to Bor
- Basically, A round where everyone signs for finality 
- A 2/3+1 attestation process after each span or similar to checkpoint interval.
- since sigs are there, we can use external/light bor nodes to sync Heimdall.

**Comment by jdkanani** [comment]
### Proposal 3

> Assuming @0xAshish's proposal is 2

Use Tendermint side-channel p2p messaging to collect sigs on valid checkpoint instead of vote based consensus on Heimdall (unlike proposal 1)

https://github.com/tendermint/tendermint/issues/476

**Steps for the checkpoint or any external state verification on Heimdall**

- The proposer will propose state-message over p2p channel
- Each validator verifies and sigs on it
- Proposer collects all sigs and broadcasts them on Heimdall
- Heimdall will take necessary action and change the state based on sigs

**Comment by vaibhavchellani** [comment]
>Each validator verifies and sigs on it

Please elaborate on how this verification happens?

Also how will we identify the transaction type in `tendermint` ?

**Comment by jdkanani** [comment]
PR #308 fixes this

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
