### ISSUE TITLE
Stargate Upgrade

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#439]

**Comment by jdkanani** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Porting ChainManager Module #437](https://github.com/maticnetwork/heimdall/issues/437) | Dec 2020 Sprint 1 | murthyvitwit | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Porting Staking Module  #436](https://github.com/maticnetwork/heimdall/issues/436) | Dec 2020 Sprint 1 | murthyvitwit | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Add sideTx processor in Heimdall — similar to the old one — https://github.com/maticnetwork/heimdall/blob/e58da51d56857bd3d2f61c8e7b22f4ff024bac75/app/side_tx_processor.go #435](https://github.com/maticnetwork/heimdall/issues/435) | Dec 2020 Sprint 1 | jdkanani | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Porting Clerk Module to Stargate #431](https://github.com/maticnetwork/heimdall/issues/431) | Dec 2020 Sprint 1 | temaniarpit27 | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Fix CI for heimdall v2 #426](https://github.com/maticnetwork/heimdall/issues/426) | Dec 2020 Sprint 1 | anilCSE | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Use gentxutil instead of genesis state #424](https://github.com/maticnetwork/heimdall/issues/424) | Dec 2020 Sprint 1 | jdkanani | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [ Error while `heimdall init` command when genesis file already exist. #428](https://github.com/maticnetwork/heimdall/issues/428) | Dec 2020 Sprint 1 | murthyvitwit | Closed


###### do-not-edit-end-codetree-epic-issues

**Comment by temaniarpit27** [comment]
Heimdall V2 issue
Closing this
