### ISSUE TITLE
Question: Why doesn't a proposer send a checkpoint?

### ISSUE THREAD

**Issue by plutalov** [maticnetwork/heimdall#732]
Hi! I've done some research on proposing a checkpoint process and noticed that proposers tend not to send the checkpoint to the Heimdall network even when it's 255+ blocks since the previous. In that case, a current proposer usually is replaced by some validator set change in the EndBlocker.

I'd like to figure out what is the reason for such behavior and what is the need to change a proposer on any set update. I can provide some examples or statistics if needed.

Could someone elaborate on it or provide a relevant doc? Thanks in advance!

**Comment by ssandeep** [comment]
Hi @plutalov , the bridge waits for `checkpoint_poll_interval` before initiating preparation of the checkpoint. This value is configured in `heimdall-config.toml` file. So even though it's 255+ blocks since the previous checkpoint, the bridge doesn't initiate the process until `checkpoint_poll_interval` time has elapsed.
